### ISSUE TITLE
 缺少对应的c头文件，方便用jexract去生成abi

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [dreamlike-ocean/PanamaUring#25]
部分头文件可能会有自己加的和配置的部分，这块的头文件是没见到的。不方便查看和维护。 我自己生成出来发现，shm_unlike这个函数就不会有。

**Comment by dreamlike-ocean** [comment]
@            return ((int) shm_unlink$MH.invoke(name));😂笔误写错了

**Comment by dreamlike-ocean** [comment]
这一部分确实是jexract生成的 但是发现生成出来噪音太大 正在做瘦身
