### ISSUE TITLE
移除mutiny依赖

### ISSUE THREAD

**Issue by dreamlike-ocean** [dreamlike-ocean/PanamaUring#43]
之前为了实现reactive式的api 引入了mutiny作为统一的异步视图
但是由于io_uring本身cancel的特性导致并不能很好的适配上该库的cancel语义
可能会存在内存不安全，内存泄露的情况，且适配代码复杂度较高
在参考monoio api之后，采用canceltoken+显式转移所有权和系统调用值的方案

**Comment by He-Pin** [comment]
试试pekko stream？
